project:
  type: book

book:
  title: "LaPros"
  author: "Võ Chí Công"
  date: "2022/8/25"
  downloads: pdf
  chapters:
    - index.qmd
    - doc/20-method.qmd
    - doc/90-final.qmd
  repo-url: https://github.com/Tre-Xanh/lapros

comments:
  hypothesis: true

crossref:
  eq-prefix: Eq
  chapters: false

format:
  html:
    theme: cosmo
    include-before-body: doc/preamble.md
  pdf:
    documentclass: scrreprt
    include-in-header: doc/preamble.tex
